### ISSUE TITLE
session start/end always flips to current date/time

### ISSUE THREAD

**Issue by humarf** [capape/observation-manager#34]
Hello,
I installed 1.6.0RC3 from releases tab. When creating a new observation session start/end date always flips to current date/time no matter weather you select a different date. It cannot be changed afterwards. Could you check that, please?
Best regards
humarf

**Comment by capape** [comment]
Hi,

Thank you for let me know it. I'll take a look

**Comment by capape** [comment]
Fixed in v1.6.0-RC4. Please confirm

**Comment by humarf** [comment]
It works. Thank you!
